package account

import (
	"errors"

	"gorm.io/gorm"
)

// Repository handles all database operations for accounts.
// It receives a *gorm.DB instance so it can participate in
// transactions managed by the service layer.
type Repository struct {
	db *gorm.DB
}

// NewRepository creates a new account Repository with the given DB connection.
func NewRepository(db *gorm.DB) *Repository {
	return &Repository{db: db}
}

// Create inserts a new account record into the database.
// The account's UUID is generated by the BeforeCreate GORM hook.
func (r *Repository) Create(account *Account) error {
	return r.db.Create(account).Error
}

// FindByID retrieves an account by its UUID primary key.
// Returns gorm.ErrRecordNotFound if no account exists with that ID.
func (r *Repository) FindByID(id string) (*Account, error) {
	var account Account
	err := r.db.Where("id = ?", id).First(&account).Error
	if err != nil {
		return nil, err
	}
	return &account, nil
}

// FindByEmail retrieves an account by the owner's email address.
// Returns gorm.ErrRecordNotFound if no account exists with that email.
func (r *Repository) FindByEmail(email string) (*Account, error) {
	var account Account
	err := r.db.Where("email = ?", email).First(&account).Error
	if err != nil {
		return nil, err
	}
	return &account, nil
}

// ExistsByEmail checks whether an account with the given email already exists.
// Used to enforce uniqueness before attempting an insert.
func (r *Repository) ExistsByEmail(email string) (bool, error) {
	var count int64
	err := r.db.Model(&Account{}).Where("email = ?", email).Count(&count).Error
	if err != nil {
		return false, err
	}
	return count > 0, nil
}

// FindByIDForUpdate retrieves an account with a row-level lock (SELECT FOR UPDATE).
// Must be called within a transaction. Used before any balance modification
// to prevent race conditions in concurrent deposit/withdraw/transfer operations.
func (r *Repository) FindByIDForUpdate(tx *gorm.DB, id string) (*Account, error) {
	var account Account
	err := tx.Set("gorm:query_option", "FOR UPDATE").
		Where("id = ?", id).
		First(&account).Error
	if err != nil {
		return nil, err
	}
	return &account, nil
}

// UpdateBalance saves a new balance value for the given account.
// Always call within a transaction and after FindByIDForUpdate.
// Uses update_fields to avoid accidentally overwriting other columns.
func (r *Repository) UpdateBalance(tx *gorm.DB, account *Account) error {
	return tx.Model(account).
		Select("balance", "updated_at").
		Updates(account).Error
}

// IsNotFound is a helper that returns true if the error is a GORM "record not found" error.
// Centralizes this check so service/handler layers don't import gorm directly just for this.
func IsNotFound(err error) bool {
	return errors.Is(err, gorm.ErrRecordNotFound)
}
